// Mocks generated by Mockito 5.4.6 from annotations
// in fihirana/test/translation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fihirana/services/language_detection_service.dart' as _i5;
import 'package:fihirana/services/translation_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationService extends _i1.Mock
    implements _i2.TranslationService {
  MockTranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get supportedLanguagesMap => (super.noSuchMethod(
        Invocation.getter(#supportedLanguagesMap),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  List<String> get supportedLanguages => (super.noSuchMethod(
        Invocation.getter(#supportedLanguages),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> translate({
    required String? text,
    String? sourceLanguage = 'auto',
    String? targetLanguage = 'en',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #translate,
          [],
          {
            #text: text,
            #sourceLanguage: sourceLanguage,
            #targetLanguage: targetLanguage,
          },
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #translate,
            [],
            {
              #text: text,
              #sourceLanguage: sourceLanguage,
              #targetLanguage: targetLanguage,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> translateText(
    String? text,
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #translateText,
          [
            text,
            from,
            to,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #translateText,
            [
              text,
              from,
              to,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<Map<String, String>> translateBatch(
    Map<String, String>? texts,
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #translateBatch,
          [
            texts,
            from,
            to,
          ],
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<String> detectLanguage(String? text) => (super.noSuchMethod(
        Invocation.method(
          #detectLanguage,
          [text],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #detectLanguage,
            [text],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  String getLanguageName(String? code) => (super.noSuchMethod(
        Invocation.method(
          #getLanguageName,
          [code],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageName,
            [code],
          ),
        ),
      ) as String);

  @override
  bool isTranslationAvailable(
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isTranslationAvailable,
          [
            from,
            to,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isLanguageSupported(String? language) => (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [language],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<String> getCachedTranslation(
    String? text,
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedTranslation,
          [
            text,
            from,
            to,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getCachedTranslation,
            [
              text,
              from,
              to,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> isModelDownloaded(String? language) => (super.noSuchMethod(
        Invocation.method(
          #isModelDownloaded,
          [language],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> downloadModel(String? language) => (super.noSuchMethod(
        Invocation.method(
          #downloadModel,
          [language],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LanguageDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageDetectionService extends _i1.Mock
    implements _i5.LanguageDetectionService {
  MockLanguageDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> detectLanguage(String? text) => (super.noSuchMethod(
        Invocation.method(
          #detectLanguage,
          [text],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #detectLanguage,
            [text],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> getSourceLanguage(String? text) => (super.noSuchMethod(
        Invocation.method(
          #getSourceLanguage,
          [text],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getSourceLanguage,
            [text],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> needsTranslation(
    String? text,
    String? targetLanguage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #needsTranslation,
          [
            text,
            targetLanguage,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<double> getConfidence(
    String? text,
    String? detectedLanguage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConfidence,
          [
            text,
            detectedLanguage,
          ],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<Map<String, double>> getLanguagePredictions(String? text) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguagePredictions,
          [text],
        ),
        returnValue: _i3.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i3.Future<Map<String, double>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
