class InspiringVerses {
  static const List<Map<String, dynamic>> list = [
    // Pentateuch
    {'book': 'Genesis', 'chapter': 1, 'verse': 1},
    {'book': 'Genesis', 'chapter': 1, 'verse': 27},
    {'book': 'Genesis', 'chapter': 12, 'verse': 2},
    {'book': 'Genesis', 'chapter': 28, 'verse': 15},
    {'book': 'Genesis', 'chapter': 50, 'verse': 20},
    {'book': 'Exodus', 'chapter': 14, 'verse': 14},
    {'book': 'Exodus', 'chapter': 15, 'verse': 2},
    {'book': 'Exodus', 'chapter': 20, 'verse': 12},
    {'book': 'Exodus', 'chapter': 33, 'verse': 14},
    {'book': 'Leviticus', 'chapter': 19, 'verse': 18},
    {'book': 'Numbers', 'chapter': 6, 'verse': 24},
    {'book': 'Numbers', 'chapter': 6, 'verse': 25},
    {'book': 'Numbers', 'chapter': 6, 'verse': 26},
    {'book': 'Deuteronomy', 'chapter': 6, 'verse': 5},
    {'book': 'Deuteronomy', 'chapter': 7, 'verse': 9},
    {'book': 'Deuteronomy', 'chapter': 20, 'verse': 4},
    {'book': 'Deuteronomy', 'chapter': 31, 'verse': 6},
    {'book': 'Deuteronomy', 'chapter': 31, 'verse': 8},
    {'book': 'Deuteronomy', 'chapter': 33, 'verse': 27},

    // Historical Books
    {'book': 'Joshua', 'chapter': 1, 'verse': 5},
    {'book': 'Joshua', 'chapter': 1, 'verse': 9},
    {'book': 'Joshua', 'chapter': 24, 'verse': 15},
    {'book': 'Ruth', 'chapter': 1, 'verse': 16},
    {'book': 'I Samuel', 'chapter': 2, 'verse': 2},
    {'book': 'I Samuel', 'chapter': 12, 'verse': 24},
    {'book': 'I Samuel', 'chapter': 16, 'verse': 7},
    {'book': 'II Samuel', 'chapter': 22, 'verse': 3},
    {'book': 'II Samuel', 'chapter': 22, 'verse': 31},
    {'book': 'I Kings', 'chapter': 8, 'verse': 56},
    {'book': 'I Chronicles', 'chapter': 16, 'verse': 11},
    {'book': 'I Chronicles', 'chapter': 16, 'verse': 34},
    {'book': 'I Chronicles', 'chapter': 29, 'verse': 11},
    {'book': 'II Chronicles', 'chapter': 7, 'verse': 14},
    {'book': 'II Chronicles', 'chapter': 16, 'verse': 9},
    {'book': 'Ezra', 'chapter': 10, 'verse': 4},
    {'book': 'Nehemiah', 'chapter': 8, 'verse': 10},
    {'book': 'Esther', 'chapter': 4, 'verse': 14},

    // Wisdom Literature
    {'book': 'Job', 'chapter': 19, 'verse': 25},
    {'book': 'Job', 'chapter': 42, 'verse': 2},
    {'book': 'Psalms', 'chapter': 1, 'verse': 1},
    {'book': 'Psalms', 'chapter': 1, 'verse': 2},
    {'book': 'Psalms', 'chapter': 1, 'verse': 3},
    {'book': 'Psalms', 'chapter': 8, 'verse': 1},
    {'book': 'Psalms', 'chapter': 9, 'verse': 1},
    {'book': 'Psalms', 'chapter': 16, 'verse': 8},
    {'book': 'Psalms', 'chapter': 16, 'verse': 11},
    {'book': 'Psalms', 'chapter': 18, 'verse': 1},
    {'book': 'Psalms', 'chapter': 18, 'verse': 2},
    {'book': 'Psalms', 'chapter': 18, 'verse': 30},
    {'book': 'Psalms', 'chapter': 19, 'verse': 1},
    {'book': 'Psalms', 'chapter': 19, 'verse': 14},
    {'book': 'Psalms', 'chapter': 23, 'verse': 1},
    {'book': 'Psalms', 'chapter': 23, 'verse': 2},
    {'book': 'Psalms', 'chapter': 23, 'verse': 3},
    {'book': 'Psalms', 'chapter': 23, 'verse': 4},
    {'book': 'Psalms', 'chapter': 23, 'verse': 5},
    {'book': 'Psalms', 'chapter': 23, 'verse': 6},
    {'book': 'Psalms', 'chapter': 25, 'verse': 4},
    {'book': 'Psalms', 'chapter': 25, 'verse': 5},
    {'book': 'Psalms', 'chapter': 27, 'verse': 1},
    {'book': 'Psalms', 'chapter': 27, 'verse': 4},
    {'book': 'Psalms', 'chapter': 27, 'verse': 14},
    {'book': 'Psalms', 'chapter': 28, 'verse': 7},
    {'book': 'Psalms', 'chapter': 29, 'verse': 11},
    {'book': 'Psalms', 'chapter': 30, 'verse': 5},
    {'book': 'Psalms', 'chapter': 31, 'verse': 24},
    {'book': 'Psalms', 'chapter': 32, 'verse': 8},
    {'book': 'Psalms', 'chapter': 34, 'verse': 4},
    {'book': 'Psalms', 'chapter': 34, 'verse': 8},
    {'book': 'Psalms', 'chapter': 34, 'verse': 17},
    {'book': 'Psalms', 'chapter': 34, 'verse': 18},
    {'book': 'Psalms', 'chapter': 37, 'verse': 4},
    {'book': 'Psalms', 'chapter': 37, 'verse': 5},
    {'book': 'Psalms', 'chapter': 37, 'verse': 7},
    {'book': 'Psalms', 'chapter': 37, 'verse': 23},
    {'book': 'Psalms', 'chapter': 40, 'verse': 1},
    {'book': 'Psalms', 'chapter': 42, 'verse': 11},
    {'book': 'Psalms', 'chapter': 46, 'verse': 1},
    {'book': 'Psalms', 'chapter': 46, 'verse': 10},
    {'book': 'Psalms', 'chapter': 51, 'verse': 10},
    {'book': 'Psalms', 'chapter': 55, 'verse': 22},
    {'book': 'Psalms', 'chapter': 56, 'verse': 3},
    {'book': 'Psalms', 'chapter': 62, 'verse': 1},
    {'book': 'Psalms', 'chapter': 62, 'verse': 6},
    {'book': 'Psalms', 'chapter': 73, 'verse': 26},
    {'book': 'Psalms', 'chapter': 84, 'verse': 11},
    {'book': 'Psalms', 'chapter': 90, 'verse': 12},
    {'book': 'Psalms', 'chapter': 91, 'verse': 1},
    {'book': 'Psalms', 'chapter': 91, 'verse': 2},
    {'book': 'Psalms', 'chapter': 91, 'verse': 11},
    {'book': 'Psalms', 'chapter': 100, 'verse': 4},
    {'book': 'Psalms', 'chapter': 100, 'verse': 5},
    {'book': 'Psalms', 'chapter': 103, 'verse': 1},
    {'book': 'Psalms', 'chapter': 103, 'verse': 2},
    {'book': 'Psalms', 'chapter': 103, 'verse': 8},
    {'book': 'Psalms', 'chapter': 103, 'verse': 12},
    {'book': 'Psalms', 'chapter': 107, 'verse': 1},
    {'book': 'Psalms', 'chapter': 118, 'verse': 6},
    {'book': 'Psalms', 'chapter': 118, 'verse': 14},
    {'book': 'Psalms', 'chapter': 118, 'verse': 24},
    {'book': 'Psalms', 'chapter': 119, 'verse': 11},
    {'book': 'Psalms', 'chapter': 119, 'verse': 105},
    {'book': 'Psalms', 'chapter': 121, 'verse': 1},
    {'book': 'Psalms', 'chapter': 121, 'verse': 2},
    {'book': 'Psalms', 'chapter': 121, 'verse': 7},
    {'book': 'Psalms', 'chapter': 121, 'verse': 8},
    {'book': 'Psalms', 'chapter': 127, 'verse': 1},
    {'book': 'Psalms', 'chapter': 136, 'verse': 1},
    {'book': 'Psalms', 'chapter': 139, 'verse': 14},
    {'book': 'Psalms', 'chapter': 139, 'verse': 23},
    {'book': 'Psalms', 'chapter': 139, 'verse': 24},
    {'book': 'Psalms', 'chapter': 143, 'verse': 8},
    {'book': 'Psalms', 'chapter': 143, 'verse': 10},
    {'book': 'Psalms', 'chapter': 145, 'verse': 18},
    {'book': 'Psalms', 'chapter': 147, 'verse': 3},
    {'book': 'Psalms', 'chapter': 150, 'verse': 6},
    {'book': 'Proverbs', 'chapter': 3, 'verse': 5},
    {'book': 'Proverbs', 'chapter': 3, 'verse': 6},
    {'book': 'Proverbs', 'chapter': 4, 'verse': 23},
    {'book': 'Proverbs', 'chapter': 16, 'verse': 3},
    {'book': 'Proverbs', 'chapter': 16, 'verse': 9},
    {'book': 'Proverbs', 'chapter': 17, 'verse': 17},
    {'book': 'Proverbs', 'chapter': 17, 'verse': 22},
    {'book': 'Proverbs', 'chapter': 18, 'verse': 10},
    {'book': 'Proverbs', 'chapter': 19, 'verse': 21},
    {'book': 'Proverbs', 'chapter': 22, 'verse': 6},
    {'book': 'Proverbs', 'chapter': 27, 'verse': 17},
    {'book': 'Proverbs', 'chapter': 30, 'verse': 5},
    {'book': 'Proverbs', 'chapter': 31, 'verse': 25},
    {'book': 'Proverbs', 'chapter': 31, 'verse': 30},
    {'book': 'Ecclesiastes', 'chapter': 3, 'verse': 1},
    {'book': 'Ecclesiastes', 'chapter': 3, 'verse': 11},
    {'book': 'Ecclesiastes', 'chapter': 4, 'verse': 9},
    {'book': 'Ecclesiastes', 'chapter': 4, 'verse': 10},
    {'book': 'Ecclesiastes', 'chapter': 12, 'verse': 13},
    {'book': 'Song of Solomon', 'chapter': 2, 'verse': 16},
    {'book': 'Song of Solomon', 'chapter': 8, 'verse': 6},
    {'book': 'Song of Solomon', 'chapter': 8, 'verse': 7},

    // Major Prophets
    {'book': 'Isaiah', 'chapter': 6, 'verse': 8},
    {'book': 'Isaiah', 'chapter': 9, 'verse': 6},
    {'book': 'Isaiah', 'chapter': 26, 'verse': 3},
    {'book': 'Isaiah', 'chapter': 26, 'verse': 4},
    {'book': 'Isaiah', 'chapter': 40, 'verse': 8},
    {'book': 'Isaiah', 'chapter': 40, 'verse': 28},
    {'book': 'Isaiah', 'chapter': 40, 'verse': 29},
    {'book': 'Isaiah', 'chapter': 40, 'verse': 31},
    {'book': 'Isaiah', 'chapter': 41, 'verse': 10},
    {'book': 'Isaiah', 'chapter': 41, 'verse': 13},
    {'book': 'Isaiah', 'chapter': 43, 'verse': 1},
    {'book': 'Isaiah', 'chapter': 43, 'verse': 2},
    {'book': 'Isaiah', 'chapter': 43, 'verse': 19},
    {'book': 'Isaiah', 'chapter': 53, 'verse': 5},
    {'book': 'Isaiah', 'chapter': 54, 'verse': 10},
    {'book': 'Isaiah', 'chapter': 54, 'verse': 17},
    {'book': 'Isaiah', 'chapter': 55, 'verse': 6},
    {'book': 'Isaiah', 'chapter': 55, 'verse': 8},
    {'book': 'Isaiah', 'chapter': 55, 'verse': 9},
    {'book': 'Isaiah', 'chapter': 60, 'verse': 1},
    {'book': 'Jeremiah', 'chapter': 1, 'verse': 5},
    {'book': 'Jeremiah', 'chapter': 29, 'verse': 11},
    {'book': 'Jeremiah', 'chapter': 29, 'verse': 12},
    {'book': 'Jeremiah', 'chapter': 29, 'verse': 13},
    {'book': 'Jeremiah', 'chapter': 33, 'verse': 3},
    {'book': 'Lamentations', 'chapter': 3, 'verse': 22},
    {'book': 'Lamentations', 'chapter': 3, 'verse': 23},
    {'book': 'Lamentations', 'chapter': 3, 'verse': 24},
    {'book': 'Lamentations', 'chapter': 3, 'verse': 25},
    {'book': 'Ezekiel', 'chapter': 36, 'verse': 26},
    {'book': 'Daniel', 'chapter': 2, 'verse': 22},
    {'book': 'Daniel', 'chapter': 12, 'verse': 3},

    // Minor Prophets
    {'book': 'Hosea', 'chapter': 6, 'verse': 3},
    {'book': 'Joel', 'chapter': 2, 'verse': 28},
    {'book': 'Amos', 'chapter': 5, 'verse': 24},
    {'book': 'Jonah', 'chapter': 2, 'verse': 9},
    {'book': 'Micah', 'chapter': 6, 'verse': 8},
    {'book': 'Micah', 'chapter': 7, 'verse': 7},
    {'book': 'Micah', 'chapter': 7, 'verse': 8},
    {'book': 'Micah', 'chapter': 7, 'verse': 18},
    {'book': 'Nahum', 'chapter': 1, 'verse': 7},
    {'book': 'Habakkuk', 'chapter': 3, 'verse': 19},
    {'book': 'Zephaniah', 'chapter': 3, 'verse': 17},
    {'book': 'Haggai', 'chapter': 2, 'verse': 9},
    {'book': 'Zechariah', 'chapter': 4, 'verse': 6},
    {'book': 'Zechariah', 'chapter': 9, 'verse': 9},
    {'book': 'Malachi', 'chapter': 3, 'verse': 10},
    {'book': 'Malachi', 'chapter': 4, 'verse': 2},

    // Gospels
    {'book': 'Matthew', 'chapter': 4, 'verse': 4},
    {'book': 'Matthew', 'chapter': 5, 'verse': 3},
    {'book': 'Matthew', 'chapter': 5, 'verse': 4},
    {'book': 'Matthew', 'chapter': 5, 'verse': 5},
    {'book': 'Matthew', 'chapter': 5, 'verse': 6},
    {'book': 'Matthew', 'chapter': 5, 'verse': 7},
    {'book': 'Matthew', 'chapter': 5, 'verse': 8},
    {'book': 'Matthew', 'chapter': 5, 'verse': 9},
    {'book': 'Matthew', 'chapter': 5, 'verse': 14},
    {'book': 'Matthew', 'chapter': 5, 'verse': 16},
    {'book': 'Matthew', 'chapter': 6, 'verse': 14},
    {'book': 'Matthew', 'chapter': 6, 'verse': 21},
    {'book': 'Matthew', 'chapter': 6, 'verse': 33},
    {'book': 'Matthew', 'chapter': 6, 'verse': 34},
    {'book': 'Matthew', 'chapter': 7, 'verse': 7},
    {'book': 'Matthew', 'chapter': 7, 'verse': 8},
    {'book': 'Matthew', 'chapter': 11, 'verse': 28},
    {'book': 'Matthew', 'chapter': 11, 'verse': 29},
    {'book': 'Matthew', 'chapter': 11, 'verse': 30},
    {'book': 'Matthew', 'chapter': 18, 'verse': 20},
    {'book': 'Matthew', 'chapter': 19, 'verse': 26},
    {'book': 'Matthew', 'chapter': 22, 'verse': 37},
    {'book': 'Matthew', 'chapter': 22, 'verse': 39},
    {'book': 'Matthew', 'chapter': 28, 'verse': 19},
    {'book': 'Matthew', 'chapter': 28, 'verse': 20},
    {'book': 'Mark', 'chapter': 9, 'verse': 23},
    {'book': 'Mark', 'chapter': 10, 'verse': 27},
    {'book': 'Mark', 'chapter': 11, 'verse': 24},
    {'book': 'Luke', 'chapter': 1, 'verse': 37},
    {'book': 'Luke', 'chapter': 6, 'verse': 31},
    {'book': 'Luke', 'chapter': 6, 'verse': 38},
    {'book': 'Luke', 'chapter': 11, 'verse': 9},
    {'book': 'Luke', 'chapter': 12, 'verse': 34},
    {'book': 'John', 'chapter': 1, 'verse': 1},
    {'book': 'John', 'chapter': 1, 'verse': 12},
    {'book': 'John', 'chapter': 1, 'verse': 14},
    {'book': 'John', 'chapter': 3, 'verse': 16},
    {'book': 'John', 'chapter': 3, 'verse': 17},
    {'book': 'John', 'chapter': 8, 'verse': 12},
    {'book': 'John', 'chapter': 8, 'verse': 32},
    {'book': 'John', 'chapter': 10, 'verse': 10},
    {'book': 'John', 'chapter': 10, 'verse': 27},
    {'book': 'John', 'chapter': 10, 'verse': 28},
    {'book': 'John', 'chapter': 11, 'verse': 25},
    {'book': 'John', 'chapter': 13, 'verse': 34},
    {'book': 'John', 'chapter': 13, 'verse': 35},
    {'book': 'John', 'chapter': 14, 'verse': 1},
    {'book': 'John', 'chapter': 14, 'verse': 6},
    {'book': 'John', 'chapter': 14, 'verse': 15},
    {'book': 'John', 'chapter': 14, 'verse': 27},
    {'book': 'John', 'chapter': 15, 'verse': 5},
    {'book': 'John', 'chapter': 15, 'verse': 13},
    {'book': 'John', 'chapter': 16, 'verse': 33},

    // Acts & Epistles
    {'book': 'Acts', 'chapter': 1, 'verse': 8},
    {'book': 'Acts', 'chapter': 2, 'verse': 21},
    {'book': 'Acts', 'chapter': 4, 'verse': 12},
    {'book': 'Acts', 'chapter': 16, 'verse': 31},
    {'book': 'Acts', 'chapter': 20, 'verse': 35},
    {'book': 'Romans', 'chapter': 1, 'verse': 16},
    {'book': 'Romans', 'chapter': 3, 'verse': 23},
    {'book': 'Romans', 'chapter': 5, 'verse': 1},
    {'book': 'Romans', 'chapter': 5, 'verse': 8},
    {'book': 'Romans', 'chapter': 6, 'verse': 23},
    {'book': 'Romans', 'chapter': 8, 'verse': 1},
    {'book': 'Romans', 'chapter': 8, 'verse': 18},
    {'book': 'Romans', 'chapter': 8, 'verse': 28},
    {'book': 'Romans', 'chapter': 8, 'verse': 31},
    {'book': 'Romans', 'chapter': 8, 'verse': 37},
    {'book': 'Romans', 'chapter': 8, 'verse': 38},
    {'book': 'Romans', 'chapter': 8, 'verse': 39},
    {'book': 'Romans', 'chapter': 10, 'verse': 9},
    {'book': 'Romans', 'chapter': 10, 'verse': 13},
    {'book': 'Romans', 'chapter': 12, 'verse': 1},
    {'book': 'Romans', 'chapter': 12, 'verse': 2},
    {'book': 'Romans', 'chapter': 12, 'verse': 12},
    {'book': 'Romans', 'chapter': 12, 'verse': 21},
    {'book': 'Romans', 'chapter': 15, 'verse': 13},
    {'book': 'I Corinthians', 'chapter': 1, 'verse': 18},
    {'book': 'I Corinthians', 'chapter': 2, 'verse': 9},
    {'book': 'I Corinthians', 'chapter': 3, 'verse': 16},
    {'book': 'I Corinthians', 'chapter': 10, 'verse': 13},
    {'book': 'I Corinthians', 'chapter': 10, 'verse': 31},
    {'book': 'I Corinthians', 'chapter': 13, 'verse': 4},
    {'book': 'I Corinthians', 'chapter': 13, 'verse': 5},
    {'book': 'I Corinthians', 'chapter': 13, 'verse': 6},
    {'book': 'I Corinthians', 'chapter': 13, 'verse': 7},
    {'book': 'I Corinthians', 'chapter': 13, 'verse': 13},
    {'book': 'I Corinthians', 'chapter': 15, 'verse': 57},
    {'book': 'I Corinthians', 'chapter': 15, 'verse': 58},
    {'book': 'I Corinthians', 'chapter': 16, 'verse': 13},
    {'book': 'I Corinthians', 'chapter': 16, 'verse': 14},
    {'book': 'II Corinthians', 'chapter': 1, 'verse': 3},
    {'book': 'II Corinthians', 'chapter': 1, 'verse': 4},
    {'book': 'II Corinthians', 'chapter': 4, 'verse': 16},
    {'book': 'II Corinthians', 'chapter': 4, 'verse': 17},
    {'book': 'II Corinthians', 'chapter': 5, 'verse': 7},
    {'book': 'II Corinthians', 'chapter': 5, 'verse': 17},
    {'book': 'II Corinthians', 'chapter': 9, 'verse': 8},
    {'book': 'II Corinthians', 'chapter': 12, 'verse': 9},
    {'book': 'Galatians', 'chapter': 2, 'verse': 20},
    {'book': 'Galatians', 'chapter': 5, 'verse': 1},
    {'book': 'Galatians', 'chapter': 5, 'verse': 13},
    {'book': 'Galatians', 'chapter': 5, 'verse': 22},
    {'book': 'Galatians', 'chapter': 5, 'verse': 23},
    {'book': 'Galatians', 'chapter': 6, 'verse': 2},
    {'book': 'Galatians', 'chapter': 6, 'verse': 9},
    {'book': 'Ephesians', 'chapter': 2, 'verse': 8},
    {'book': 'Ephesians', 'chapter': 2, 'verse': 9},
    {'book': 'Ephesians', 'chapter': 2, 'verse': 10},
    {'book': 'Ephesians', 'chapter': 3, 'verse': 20},
    {'book': 'Ephesians', 'chapter': 4, 'verse': 2},
    {'book': 'Ephesians', 'chapter': 4, 'verse': 32},
    {'book': 'Ephesians', 'chapter': 5, 'verse': 1},
    {'book': 'Ephesians', 'chapter': 5, 'verse': 2},
    {'book': 'Ephesians', 'chapter': 6, 'verse': 10},
    {'book': 'Ephesians', 'chapter': 6, 'verse': 11},
    {'book': 'Philippians', 'chapter': 1, 'verse': 6},
    {'book': 'Philippians', 'chapter': 2, 'verse': 3},
    {'book': 'Philippians', 'chapter': 2, 'verse': 4},
    {'book': 'Philippians', 'chapter': 3, 'verse': 13},
    {'book': 'Philippians', 'chapter': 3, 'verse': 14},
    {'book': 'Philippians', 'chapter': 4, 'verse': 4},
    {'book': 'Philippians', 'chapter': 4, 'verse': 6},
    {'book': 'Philippians', 'chapter': 4, 'verse': 7},
    {'book': 'Philippians', 'chapter': 4, 'verse': 8},
    {'book': 'Philippians', 'chapter': 4, 'verse': 13},
    {'book': 'Philippians', 'chapter': 4, 'verse': 19},
    {'book': 'Colossians', 'chapter': 3, 'verse': 2},
    {'book': 'Colossians', 'chapter': 3, 'verse': 12},
    {'book': 'Colossians', 'chapter': 3, 'verse': 13},
    {'book': 'Colossians', 'chapter': 3, 'verse': 14},
    {'book': 'Colossians', 'chapter': 3, 'verse': 15},
    {'book': 'Colossians', 'chapter': 3, 'verse': 17},
    {'book': 'Colossians', 'chapter': 3, 'verse': 23},
    {'book': 'I Thessalonians', 'chapter': 5, 'verse': 11},
    {'book': 'I Thessalonians', 'chapter': 5, 'verse': 16},
    {'book': 'I Thessalonians', 'chapter': 5, 'verse': 17},
    {'book': 'I Thessalonians', 'chapter': 5, 'verse': 18},
    {'book': 'II Thessalonians', 'chapter': 3, 'verse': 3},
    {'book': 'I Timothy', 'chapter': 4, 'verse': 12},
    {'book': 'I Timothy', 'chapter': 6, 'verse': 6},
    {'book': 'I Timothy', 'chapter': 6, 'verse': 12},
    {'book': 'II Timothy', 'chapter': 1, 'verse': 7},
    {'book': 'II Timothy', 'chapter': 3, 'verse': 16},
    {'book': 'II Timothy', 'chapter': 4, 'verse': 7},
    {'book': 'Hebrews', 'chapter': 4, 'verse': 12},
    {'book': 'Hebrews', 'chapter': 4, 'verse': 16},
    {'book': 'Hebrews', 'chapter': 10, 'verse': 23},
    {'book': 'Hebrews', 'chapter': 10, 'verse': 24},
    {'book': 'Hebrews', 'chapter': 11, 'verse': 1},
    {'book': 'Hebrews', 'chapter': 11, 'verse': 6},
    {'book': 'Hebrews', 'chapter': 12, 'verse': 1},
    {'book': 'Hebrews', 'chapter': 12, 'verse': 2},
    {'book': 'Hebrews', 'chapter': 13, 'verse': 5},
    {'book': 'Hebrews', 'chapter': 13, 'verse': 6},
    {'book': 'Hebrews', 'chapter': 13, 'verse': 8},
    {'book': 'James', 'chapter': 1, 'verse': 2},
    {'book': 'James', 'chapter': 1, 'verse': 3},
    {'book': 'James', 'chapter': 1, 'verse': 5},
    {'book': 'James', 'chapter': 1, 'verse': 12},
    {'book': 'James', 'chapter': 1, 'verse': 17},
    {'book': 'James', 'chapter': 1, 'verse': 22},
    {'book': 'James', 'chapter': 4, 'verse': 7},
    {'book': 'James', 'chapter': 4, 'verse': 8},
    {'book': 'James', 'chapter': 4, 'verse': 10},
    {'book': 'I Peter', 'chapter': 2, 'verse': 9},
    {'book': 'I Peter', 'chapter': 5, 'verse': 6},
    {'book': 'I Peter', 'chapter': 5, 'verse': 7},
    {'book': 'I Peter', 'chapter': 5, 'verse': 10},
    {'book': 'II Peter', 'chapter': 3, 'verse': 9},
    {'book': 'I John', 'chapter': 1, 'verse': 9},
    {'book': 'I John', 'chapter': 3, 'verse': 1},
    {'book': 'I John', 'chapter': 3, 'verse': 18},
    {'book': 'I John', 'chapter': 4, 'verse': 4},
    {'book': 'I John', 'chapter': 4, 'verse': 7},
    {'book': 'I John', 'chapter': 4, 'verse': 8},
    {'book': 'I John', 'chapter': 4, 'verse': 9},
    {'book': 'I John', 'chapter': 4, 'verse': 10},
    {'book': 'I John', 'chapter': 4, 'verse': 11},
    {'book': 'I John', 'chapter': 4, 'verse': 12},
    {'book': 'I John', 'chapter': 4, 'verse': 16},
    {'book': 'I John', 'chapter': 4, 'verse': 18},
    {'book': 'I John', 'chapter': 4, 'verse': 19},
    {'book': 'I John', 'chapter': 5, 'verse': 14},
    {'book': 'Revelation of John', 'chapter': 3, 'verse': 20},
    {'book': 'Revelation of John', 'chapter': 21, 'verse': 4},
    {'book': 'Revelation of John', 'chapter': 22, 'verse': 13},
  ];
}
